GiganticMinecraft/seichi-portal-api-schema

- .github/workflows/lint-yml.yml
> ci: run yamllint

- .github/actions/redocly-cli/action.yml
- .github/workflows/lint-openapi.yml
- .github/workflows/pub-docs.yml
ReDoc（SwaggerのEditorをもうちょっと見やすくした感じ）を生成し、GitHubPagesに公開する
> ci: publish redoc with gh-pages

- schema/paths/forms/eachForm.yml
- schema/paths/forms/index.yml
> feat: パラムやクエリの型が合わない場合は400を返す

- docker-compose.yml
- schema/paths/forms/eachForm.yml
- schema/paths/forms/types/form.yml
- schema/paths/forms/types/question.yml
ほか
* TODOを追加
* redoclyのコンテナをdocker-compose.ymlに追加
> requiredがうまく機能していなかったのを修正

- schema/paths/forms/eachForm.yml
- schema/paths/forms/types/form.yml
- schema/paths/forms/types/question.yml
frontend側がcamelCaseに対応していないっぽい
> fix: remove name from formId param

- renovate.json
> chore: add renovate

- schema/paths/forms/types/questions.yml
- schema/paths/forms/types/validation.yml
- schema/paths/forms/types/validations.yml
> feat: add validations

- schema/paths/forms/eachForm.yml
- schema/paths/forms/types/form.yml
> feat: form must have own revision_id

- README.md
> docs: add docs

- README.md
> docs: change repo name

- schema/paths/forms/eachForm.yml
- schema/paths/forms/types/form.yml
- refactor: flatten and remove form_info
> refactor: remove form info

- schema/paths/forms/index.yml
> fix: フォーム一覧取得時のレスポンスのスキーマに`form_settings`を追加

- schema/errors/errorResponses.yml
- schema/openapi.yml
- schema/paths/forms/index.yml
- schema/paths/forms/specifyForm/index.yml
- schema/paths/forms/types/form.yml
> /forms/{formId}を再定義する

- schema/paths/forms/index.yml
- schema/paths/forms/specifyForm/index.yml
- schema/types/forms/components.yml
- schema/types/forms/definitions.yml
- schema/types/forms/parameters.yml
formsディレクトリにあるのでformのcomponentであることはわかりきっているし、そうでないのであればそこにあるべきではないので。
先に #77 をマージしてください。
> `components`の`form_` prefix を削除する

- schema/openapi.yml
- schema/paths/forms/specifyForm/answers/index.yml
- schema/paths/forms/states/index.yml
- schema/types/forms/components.yml
- schema/types/forms/definitions.yml
- schema/types/users/components.yml
> フォームに対してつけられるラベルの一覧を返すエントリポイントの定義

- schema/errors/errorResponses.yml
- schema/openapi.yml
- schema/paths/forms/labels/index.yml
- schema/types/forms/components.yml
- schema/types/forms/definitions.yml
> フォームラベルを削除できるエントリポイント定義

- schema/paths/forms/labels/index.yml
- schema/types/forms/components.yml
- schema/types/forms/definitions.yml
- schema/types/forms/parameters.yml
ラベルの操作でパラメータを追加することで、どこに対してつけられるラベルかを指定できるようにしました。
> ラベルの作成・削除・取得でパラメータを指定するように

- schema/openapi.yml
- schema/paths/forms/answers/index.yml
#87 を先にマージしてください。
マージしたらrebaseをしてください。
> フォームの回答を送信するエントリポイントを定義する

- schema/openapi.yml
- schema/paths/forms/answers/comment/index.yml
- schema/paths/forms/answers/index.yml
- schema/types/forms/components.yml
- schema/types/forms/definitions.yml
#88 を先にマージしてください。
マージしたらrebaseをしてください。
> フォームの回答に対して残すことができるコメントのエントリポイントを定義する

- schema/paths/forms/index.yml
> offsetの下限値が1になっていたのを修正

- schema/paths/forms/specifyForm/index.yml
- schema/types/forms/components.yml
- schema/types/forms/parameters.yml
> webhookの設定を追加

- schema/openapi.yml
> Bearerによるトークン認証を定義する

- schema/types/forms/components.yml
> feat: フォームの質問に対してrequiredをつけられるようにする
